apiVersion: v1
kind: Pod
metadata:
  name: oom-pod
spec:
  containers:
  - name: memory-eater
    image: polysquare/stress-ng
    # Stress memory: 100MB > Limit 50MB
    args: ["--vm", "1", "--vm-bytes", "100M", "--timeout", "60s"]
    resources:
      limits:
        memory: "50Mi"
