apiVersion: v1
kind: Pod
metadata:
  name: tolerant-pod
spec:
  containers:
  - name: nginx
    image: nginx:alpine
  tolerations:
  - key: "specific"
    operator: "Equal"
    value: "workload"
    effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: minikube-m04
