apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - mountPath: "/data"
          name: my-storage
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: local-pvc
