apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: nginx
    image: nginx:alpine
  - name: sidecar
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
