apiVersion: v1
kind: Pod
metadata:
  name: config-demo-envfrom
spec:
  containers:
    - name: demo-container
      image: alpine
      command: ["/bin/sh", "-c", "sleep 3600"]
      envFrom:
        - configMapRef:
            name: app-config
